### PR TITLE
Only allow logged in users to view profiles

### LINKED ISSUE #140: Hide Real Names of Students from Anonymous Users

### LINKED ISSUE #143: Hide user profiles entirely from anonymous users, see #140

### PR DESCRIPTION
**Pull request by yaxollum**
Closes #143
Closes #140

### CODE REVIEW

**Comment by colourdelete** [comment]
API requests bypass this.

**Review by colourdelete — CHANGES_REQUESTED** [review]
REST API request rules should be updated using `TokenHasScope` (with preferably a `me_user` scope?) and `permissions.IsAuthenticated`

**Review by colourdelete — APPROVED** [review]
LGTM (well, I did some of these cheanges, so)

**Comment by yaxollum** [comment]
@colourdelete thanks!

**Pull request merged**
